config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes

  root 'recipes#index'
end

app/models/concerns/constants.rb
module Constants

  DIFFICULTY = %w(Easy Medium Hard)

end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base
  has_many :recipes
end

app/models/food_preference.rb
class FoodPreference < ActiveRecord::Base
  has_many :recipes
end

app/models/food_type.rb
class FoodType < ActiveRecord::Base
  has_many :recipes
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :food_type
  belongs_to :food_preference
  belongs_to :cuisine
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :sidebar_values

  def sidebar_values
    @food_preferences ||= FoodPreference.all
    @food_types ||= FoodType.all
    @cuisines ||= Cuisine.all
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  def index
    if params[:recipe].present?
      filtered_recipes(recipe_params)
    else
      @recipes = Recipe.all
    end
  end

  def filtered_recipes(recipe_params)
    @recipes = Recipe.where(recipe_params)
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def edit
  end

  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :cooking_time, :difficulty_level, :food_type_id, :food_preference_id, :cuisine_id, :ingredients, :procedure)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YummyRecipe</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render :partial => 'partials/navbar' %>

<div class="container">
  <div class="row">
    <div class="col-sm-2">
      <%= render :partial => 'partials/sidebar', locals: { food_preferences: @food_preferences,
                                                           food_types: @food_types,
                                                           cuisines: @cuisines }  %>
    </div>
    <div class="col-sm-10">
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Yummy Recipe</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Recipes', recipes_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><%= link_to "#{current_user.email}" %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to 'Login', new_user_session_path %></li>
            <li><%= link_to 'SignUp', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_sidebar.html.erb
<div class="panel panel-primary" id="panels">
  <div class="panel-heading">Food Preferences</div>
  <div class="panel-body">
    <% food_preferences.each do |fp| %>
        <p>
          <%= link_to recipes_path(recipe: { food_preference_id: fp.id }) do %>
              <%= fp.name %>
          <% end %>
        </p>
    <% end %>
  </div>
</div>
<div class="panel panel-primary" id="panels">
  <div class="panel-heading">Food Type</div>
  <div class="panel-body">
    <% food_types.each do |ft| %>
        <p>
          <%= link_to recipes_path(recipe: { food_type_id: ft.id }) do %>
              <%= ft.name %>
          <% end %>
        </p>
    <% end %>
  </div>
</div>
<div class="panel panel-primary" id="panels">
  <div class="panel-heading">Cuisine</div>
  <div class="panel-body">
    <% cuisines.each do |c| %>
        <p>
          <%= link_to recipes_path(recipe: { cuisine_id: c.id }) do %>
              <%= c.name %>
          <% end %>
        </p>
    <% end %>
  </div>
</div>

app/views/recipes/_form.html.erb
<%= simple_form_for(@recipe) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :cooking_time %>
    <%= f.input :difficulty_level, collection: Constants::DIFFICULTY, prompt: 'Please select', input_html: {class: 'select-inverse select-block'} %>
    <%= f.input :food_type_id, collection: @food_type, prompt: 'Please select', input_html: {class: 'select-inverse select-block'} %>
    <%= f.input :food_preference_id, collection: @food_preferences, prompt: 'Please select', input_html: {class: 'select-inverse select-block'} %>
    <%= f.input :cuisine_id, collection: @cuisine, prompt: 'Please select', input_html: {class: 'select-inverse select-block'} %>
    <%= f.input :ingredients %>
    <%= f.input :procedure %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<div class="col-sm-12 text-center">
  <p id="notice"><%= notice %></p>

  <% if @recipes.present? %>

      <h1>Listing Recipes</h1>
      <table class="table table-bordered recipe-list">
        <thead>
        <tr>
          <th>Title</th>
          <th>Cooking time</th>
          <th>Difficulty level</th>
          <th>Food type</th>
          <th>Food preference</th>
          <th>Cuisine</th>
          <th colspan="3"></th>
        </tr>
        </thead>
        <tbody>
        <% @recipes.each do |recipe| %>
            <tr>
              <td><%= recipe.title %></td>
              <td><%= recipe.cooking_time %></td>
              <td><%= recipe.difficulty_level %></td>
              <td><%= recipe.food_type.name %></td>
              <td><%= recipe.food_preference.name %></td>
              <td><%= recipe.cuisine.name %></td>
              <td><%= link_to 'Show', recipe, class: 'btn btn-primary btn-small' %></td>
              <% if user_signed_in? %>
                  <td><%= link_to 'Edit', edit_recipe_path(recipe),
                                  class: 'btn btn-success btn-small' %></td>
                  <td><%= link_to 'Delete', recipe, method: :delete,
                                  data: {confirm: 'Are you sure?'},
                                  class: 'btn btn-danger btn-small' %></td>
              <% end %>
            </tr>
        <% end %>
        </tbody>
      </table>
  <% else %>
      <h3><i>No recipe found...</i></h3>
  <% end %>
  <br>
  <%= link_to 'New Recipe', new_recipe_path, class: 'btn btn-default' %>
</div>

app/views/recipes/new.html.erb
<div class="col-sm-12">
  <div class="col-sm-8 col-sm-offset-2">
    <h1>New Recipe</h1>
    <%= render 'form' %>
    <%= link_to 'Cancel', recipes_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Cooking time:</strong>
  <%= @recipe.cooking_time %>
</p>

<p>
  <strong>Difficulty level:</strong>
  <%= @recipe.difficulty_level %>
</p>

<p>
  <strong>Food type:</strong>
  <%= @recipe.food_type_id %>
</p>

<p>
  <strong>Food preference:</strong>
  <%= @recipe.food_preference_id %>
</p>

<p>
  <strong>Cuisine:</strong>
  <%= @recipe.cuisine_id %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @recipe.ingredients %>
</p>

<p>
  <strong>Procedure:</strong>
  <%= @recipe.procedure %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>